basePath: /
definitions:
  main.Todos:
    properties:
      description:
        example: Reading book at 9 A.M
        type: string
      id:
        example: "1"
        type: string
      is_complete:
        example: "false"
        type: string
      title:
        example: Reading book
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: hacktiv@swagger.io
    name: API Support
  description: This is a sample service for managing todos
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Todos API
  version: "1.0"
paths:
  /todos:
    get:
      consumes:
      - application/json
      description: Get details of all todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Todos'
            type: array
      summary: Get details of all todos
      tags:
      - todos
    post:
      consumes:
      - application/json
      description: Create a new todos with the input payload
      parameters:
      - description: Create todos
        in: body
        name: todos
        required: true
        schema:
          $ref: '#/definitions/main.Todos'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Todos'
            type: array
      summary: Create a new todos
      tags:
      - todos
swagger: "2.0"
